// admin/frontend/src/components/device/DeviceCard.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Device } from "../../types/device";
import { useDeviceStore } from "../../stores/deviceStore";

const props = defineProps<{ device: Device }>();
const store = useDeviceStore();
const pingStatus = ref<"idle" | "ok" | "error">("idle");
const editing = ref(false);
const form = ref({ ...props.device });

async function handlePing() {
  try {
    pingStatus.value = "idle";
    const result = await store.ping(props.device.id);
    pingStatus.value = result.ok ? "ok" : "error";
  } catch {
    pingStatus.value = "error";
  }
  setTimeout(() => (pingStatus.value = "idle"), 3000);
}

async function handleSave() {
  await store.update(form.value as Device);
  editing.value = false;
}

async function handleDelete() {
  await store.remove(props.device.id);
}
</script>

<template>
  <div class="p-4 rounded-lg border border-zinc-800 bg-zinc-900/50">
    <template v-if="!editing">
      <div class="flex items-start justify-between">
        <div>
          <p class="font-medium">{{ device.name }}</p>
          <p class="text-xs text-zinc-500 font-mono mt-1">
            {{ device.ip_address }}:{{ device.osc_port }}
          </p>
        </div>
        <div class="flex items-center gap-1">
          <div
            class="w-2 h-2 rounded-full transition-colors"
            :class="{
              'bg-zinc-600': pingStatus === 'idle',
              'bg-green-400': pingStatus === 'ok',
              'bg-red-400': pingStatus === 'error',
            }"
          />
        </div>
      </div>
      <div class="flex gap-2 mt-3">
        <button @click="handlePing" class="text-xs text-zinc-400 hover:text-white transition-colors">
          Ping
        </button>
        <button @click="editing = true; form = { ...device }" class="text-xs text-zinc-400 hover:text-white transition-colors">
          Edit
        </button>
        <button @click="handleDelete" class="text-xs text-red-400/60 hover:text-red-400 transition-colors">
          Delete
        </button>
      </div>
    </template>

    <template v-else>
      <div class="space-y-2">
        <input v-model="form.name" class="w-full bg-zinc-800 rounded px-2 py-1 text-sm" placeholder="Name" />
        <input v-model="form.ip_address" class="w-full bg-zinc-800 rounded px-2 py-1 text-sm font-mono" placeholder="IP Address" />
        <input v-model.number="form.osc_port" type="number" class="w-full bg-zinc-800 rounded px-2 py-1 text-sm font-mono" placeholder="Port" />
        <div class="flex gap-2">
          <button @click="handleSave" class="text-xs text-orange-400 hover:text-orange-300">Save</button>
          <button @click="editing = false" class="text-xs text-zinc-400 hover:text-white">Cancel</button>
        </div>
      </div>
    </template>
  </div>
</template>

// admin/frontend/src/components/device/DeviceCard.tsx
import { useState } from "react";
import type { Device } from "../../types/device";
import { useDeviceStore } from "../../stores/device-store";
import { useNotificationStore } from "../../stores/notification-store";

export default function DeviceCard({ device }: { device: Device }) {
  const update = useDeviceStore((s) => s.update);
  const remove = useDeviceStore((s) => s.remove);
  const ping = useDeviceStore((s) => s.ping);
  const updateSoftware = useDeviceStore((s) => s.updateSoftware);
  const notify = useNotificationStore((s) => s.notify);
  const isOnline = useDeviceStore((s) => s.deviceStatuses[device.id] === "online");
  const deviceVersion = useDeviceStore((s) => s.deviceVersions[device.id]);
  const latestVersion = useDeviceStore((s) => s.latestVersion);
  const isUpdating = useDeviceStore((s) => s.updatingDevices.has(device.id));
  const updateLog = useDeviceStore((s) => s.updateLogs[device.id]);

  const isOutdated = isOnline && deviceVersion && latestVersion && deviceVersion.version !== latestVersion.hash;

  const [pingStatus, setPingStatus] = useState<"idle" | "pinging" | "ok" | "error">("idle");
  const [editing, setEditing] = useState(false);
  const [form, setForm] = useState({ ...device });
  const [showLogs, setShowLogs] = useState(false);

  async function handlePing() {
    try {
      setPingStatus("pinging");
      const result = await ping(device.id);
      if (result.ok) {
        setPingStatus("ok");
        notify("success", `Ping OK: ${device.name}`);
      } else {
        setPingStatus("error");
        notify("error", `Ping failed: ${device.name}`);
      }
    } catch {
      setPingStatus("error");
      notify("error", `Ping error: ${device.name}`);
    }
    setTimeout(() => setPingStatus("idle"), 3000);
  }

  async function handleUpdate() {
    await updateSoftware(device.id);
    setShowLogs(true);
  }

  async function handleSave() {
    await update(form as Device);
    notify("success", "Device updated successfully");
    setEditing(false);
  }

  return (
    <div className="p-5 rounded-xl border border-zinc-800/50 bg-zinc-900/80 shadow-sm transition-all duration-200 hover:border-zinc-700/50 hover:scale-[1.02]">
      {!editing ? (
        <>
          <div className="flex items-start justify-between">
            <div>
              <p className="font-medium text-zinc-200">{device.name}</p>
              <p className="text-xs text-zinc-500 font-mono mt-1">
                {device.ip_address}:{device.osc_port}
              </p>
            </div>
            <div className="relative flex h-2 w-2 items-center justify-center">
              {pingStatus === "pinging" && (
                <span className="absolute inline-flex h-full w-full rounded-full bg-zinc-400 opacity-75 animate-subtle-ping"></span>
              )}
              <div
                className={`relative inline-flex w-2 h-2 rounded-full transition-colors ${
                  pingStatus === "ok" || isOnline
                    ? "bg-green-400 shadow-[0_0_8px_rgba(74,222,128,0.5)]"
                    : pingStatus === "error" || !isOnline
                      ? "bg-red-500 shadow-[0_0_8px_rgba(239,68,68,0.5)]"
                      : "bg-zinc-600"
                }`}
              />
            </div>
          </div>

          {/* Version info */}
          {isOnline && deviceVersion && (
            <div className="flex items-center gap-2 mt-2">
              <span className="inline-flex items-center px-2 py-0.5 rounded bg-zinc-800 text-[10px] font-mono text-zinc-400 border border-zinc-700/50">
                {deviceVersion.version}
              </span>
              {isOutdated && (
                <span className="inline-flex items-center px-2 py-0.5 rounded-full bg-orange-500/10 text-[10px] font-medium text-orange-400 border border-orange-500/20">
                  Update available
                </span>
              )}
            </div>
          )}

          <div className="flex gap-3 mt-3">
            <button onClick={handlePing} className="text-xs text-zinc-400 hover:text-white transition-colors">
              Ping
            </button>
            {isOutdated && (
              <button
                onClick={handleUpdate}
                disabled={isUpdating}
                className="text-xs text-orange-400 hover:text-orange-300 transition-colors disabled:opacity-50"
              >
                {isUpdating ? "Updating..." : "Update"}
              </button>
            )}
            <button
              onClick={() => {
                setForm({ ...device });
                setEditing(true);
              }}
              className="text-xs text-zinc-400 hover:text-white transition-colors"
            >
              Edit
            </button>
            <button onClick={() => {
              remove(device.id);
              notify("info", "Device deleted");
            }} className="text-xs text-red-400/60 hover:text-red-400 transition-colors">
              Delete
            </button>
          </div>

          {/* Update logs */}
          {updateLog && (
            <div className="mt-3">
              <button
                onClick={() => setShowLogs(!showLogs)}
                className="text-[10px] text-zinc-500 hover:text-zinc-300 transition-colors"
              >
                {showLogs ? "Hide logs" : "Show logs"}
              </button>
              {showLogs && (
                <pre className="mt-1 p-2 rounded bg-zinc-950 border border-zinc-800/50 text-[10px] text-zinc-500 font-mono overflow-x-auto max-h-40 overflow-y-auto whitespace-pre-wrap">
                  {updateLog}
                </pre>
              )}
            </div>
          )}
        </>
      ) : (
        <div className="space-y-2">
          <input
            value={form.name}
            onChange={(e) => setForm({ ...form, name: e.target.value })}
            className="w-full bg-zinc-800 border border-zinc-700/50 rounded-lg px-3 py-1.5 text-sm focus:outline-none focus:border-orange-500/50 transition-colors"
            placeholder="Name"
          />
          <input
            value={form.ip_address}
            onChange={(e) => setForm({ ...form, ip_address: e.target.value })}
            className="w-full bg-zinc-800 border border-zinc-700/50 rounded-lg px-3 py-1.5 text-sm font-mono focus:outline-none focus:border-orange-500/50 transition-colors"
            placeholder="IP Address"
          />
          <input
            value={form.osc_port}
            onChange={(e) => setForm({ ...form, osc_port: Number(e.target.value) })}
            type="number"
            className="w-full bg-zinc-800 border border-zinc-700/50 rounded-lg px-3 py-1.5 text-sm font-mono focus:outline-none focus:border-orange-500/50 transition-colors"
            placeholder="Port"
          />
          <div className="flex gap-2">
            <button onClick={handleSave} className="text-xs text-orange-400 hover:text-orange-300 transition-colors">
              Save
            </button>
            <button onClick={() => setEditing(false)} className="text-xs text-zinc-400 hover:text-white transition-colors">
              Cancel
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
