// admin/frontend/src/components/timeline/TimelineToolbar.tsx
import { useNavigate } from "react-router";
import type { Timeline, Point, CurveType } from "../../types/timeline";
import { usePlaybackStore } from "../../stores/playback-store";
import { useDeviceStore } from "../../stores/device-store";

const curveTypes: CurveType[] = [
  "linear", "step", "ease-in", "ease-out", "ease-in-out", "sine", "exponential", "bezier",
];

interface Props {
  timeline: Timeline;
  selectedPoint: Point | null;
  onNameChange: (name: string) => void;
  onDurationChange: (duration: number) => void;
  onCurveTypeChange: (curveType: CurveType) => void;
  onSave: () => void;
}

export default function TimelineToolbar({
  timeline,
  selectedPoint,
  onNameChange,
  onDurationChange,
  onCurveTypeChange,
  onSave,
}: Props) {
  const navigate = useNavigate();
  const { status, start, stop, pause, resume } = usePlaybackStore();
  const { list: devices, fetchList: fetchDevices } = useDeviceStore();

  async function handlePlay(lane?: "a" | "b") {
    let devs = devices;
    if (devs.length === 0) {
      await fetchDevices();
      devs = useDeviceStore.getState().list;
    }
    if (devs.length === 0) return;
    const ids = devs.map((d) => d.id);
    await start("timeline", timeline.id, ids, lane);
  }

  return (
    <div className="flex items-center gap-4 px-5 py-2.5 border-b border-zinc-800/60 bg-zinc-900/50">
      <button onClick={() => navigate("/timelines")} className="text-zinc-500 hover:text-white text-sm transition-colors">
        &larr;
      </button>

      <input
        value={timeline.name}
        onChange={(e) => onNameChange(e.target.value)}
        className="bg-transparent border-b border-zinc-700 focus:border-orange-400 outline-none text-sm font-medium px-1 py-0.5 w-48 transition-colors"
      />

      <label className="flex items-center gap-1 text-xs text-zinc-500">
        Duration
        <input
          value={timeline.duration}
          onChange={(e) => onDurationChange(Number(e.target.value))}
          type="number"
          min={1}
          step={1}
          className="bg-zinc-800 border border-zinc-700/50 rounded-lg px-2 py-0.5 w-16 text-sm text-zinc-200 font-mono focus:outline-none focus:border-orange-500/50 transition-colors"
        />
        <span>s</span>
      </label>

      {selectedPoint && (
        <div className="flex items-center gap-2 ml-4 pl-4 border-l border-zinc-800/60">
          <span className="text-xs text-zinc-500">Curve:</span>
          <select
            value={selectedPoint.curve_type}
            onChange={(e) => onCurveTypeChange(e.target.value as CurveType)}
            className="bg-zinc-800 border border-zinc-700/50 rounded-lg px-2 py-0.5 text-xs text-zinc-200 focus:outline-none focus:border-orange-500/50 transition-colors"
          >
            {curveTypes.map((ct) => (
              <option key={ct} value={ct}>
                {ct === "bezier" ? "custom" : ct}
              </option>
            ))}
          </select>
          <span className="text-xs text-zinc-600 font-mono">
            t={selectedPoint.time.toFixed(1)}s v={selectedPoint.value.toFixed(3)}
          </span>
        </div>
      )}

      <div className="ml-auto flex items-center gap-2">
        {status.playing && (
          <>
            <button
              onClick={() => status.paused ? resume() : pause()}
              className="px-3 py-1.5 bg-yellow-600/80 hover:bg-yellow-500 rounded-lg text-sm font-medium transition-all duration-200"
            >
              {status.paused ? "Resume" : "Pause"}
            </button>
            <button
              onClick={() => stop()}
              className="px-3 py-1.5 bg-red-600/80 hover:bg-red-500 rounded-lg text-sm font-medium transition-all duration-200"
            >
              Stop
            </button>
          </>
        )}
        <button
          onClick={() => handlePlay()}
          disabled={status.playing}
          className="px-3 py-1.5 bg-green-600 hover:bg-green-500 disabled:opacity-40 disabled:cursor-not-allowed rounded-lg text-sm font-medium transition-all duration-200"
        >
          Play
        </button>
        <button
          onClick={onSave}
          className="px-4 py-1.5 bg-orange-600 hover:bg-orange-500 rounded-lg text-sm font-medium transition-all duration-200"
        >
          Save
        </button>
      </div>
    </div>
  );
}

// admin/frontend/src/components/timeline/TimelineToolbar.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import type { Timeline, Point, CurveType } from "../../types/timeline";

const props = defineProps<{
  timeline: Timeline;
  selectedPoint: Point | null;
}>();

const emit = defineEmits<{
  "update:name": [name: string];
  "update:duration": [duration: number];
  "update:curve-type": [curveType: CurveType];
  save: [];
}>();

const router = useRouter();

const curveTypes: CurveType[] = [
  "linear",
  "step",
  "ease-in",
  "ease-out",
  "ease-in-out",
  "sine",
  "exponential",
  "bezier",
];
</script>

<template>
  <div class="flex items-center gap-4 px-4 py-2 border-b border-zinc-800 bg-zinc-900/50">
    <button @click="router.push('/timelines')" class="text-zinc-500 hover:text-white text-sm">
      &larr;
    </button>

    <input
      :value="timeline.name"
      @input="emit('update:name', ($event.target as HTMLInputElement).value)"
      class="bg-transparent border-b border-zinc-700 focus:border-orange-400 outline-none text-sm font-medium px-1 py-0.5 w-48"
    />

    <label class="flex items-center gap-1 text-xs text-zinc-500">
      Duration
      <input
        :value="timeline.duration"
        @change="emit('update:duration', Number(($event.target as HTMLInputElement).value))"
        type="number"
        min="1"
        step="1"
        class="bg-zinc-800 rounded px-2 py-0.5 w-16 text-sm text-zinc-200 font-mono"
      />
      <span>s</span>
    </label>

    <div v-if="selectedPoint" class="flex items-center gap-2 ml-4 pl-4 border-l border-zinc-800">
      <span class="text-xs text-zinc-500">Curve:</span>
      <select
        :value="selectedPoint.curve_type"
        @change="emit('update:curve-type', ($event.target as HTMLSelectElement).value as CurveType)"
        class="bg-zinc-800 rounded px-2 py-0.5 text-xs text-zinc-200"
      >
        <option v-for="ct in curveTypes" :key="ct" :value="ct">{{ ct === 'bezier' ? 'custom' : ct }}</option>
      </select>
      <span class="text-xs text-zinc-600 font-mono">
        t={{ selectedPoint.time.toFixed(1) }}s v={{ selectedPoint.value.toFixed(3) }}
      </span>
    </div>

    <div class="ml-auto">
      <button
        @click="emit('save')"
        class="px-4 py-1.5 bg-orange-600 hover:bg-orange-500 rounded text-sm font-medium transition-colors"
      >
        Save
      </button>
    </div>
  </div>
</template>
